definitions:
  apperrors.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  controllers.MessageResponse:
    properties:
      message:
        type: string
    type: object
  models.Product:
    properties:
      created_at:
        type: string
      id:
        type: string
      name:
        type: string
      price:
        type: number
      quantity:
        minimum: 0
        type: integer
      sku:
        type: string
      updated_at:
        type: string
    required:
    - name
    - sku
    type: object
info:
  contact: {}
paths:
  /products:
    get:
      consumes:
      - application/json
      description: Get a list of all products
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Product'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apperrors.ErrorResponse'
      summary: Get all products
      tags:
      - products
    post:
      consumes:
      - application/json
      description: Create a new product with the provided details
      parameters:
      - description: Product to create
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/models.Product'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Product'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperrors.ErrorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/apperrors.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apperrors.ErrorResponse'
      summary: Create a new product
      tags:
      - products
  /products/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a product by its ID
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          schema:
            $ref: '#/definitions/controllers.MessageResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperrors.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/apperrors.ErrorResponse'
      summary: Delete a product by ID
      tags:
      - products
    get:
      consumes:
      - application/json
      description: Get a product by its ID
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Product'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperrors.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/apperrors.ErrorResponse'
      summary: Get a product by ID
      tags:
      - products
    put:
      consumes:
      - application/json
      description: Update a product by its ID with the provided details
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: string
      - description: Product to update
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/models.Product'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Product'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperrors.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/apperrors.ErrorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/apperrors.ErrorResponse'
      summary: Update a product by ID
      tags:
      - products
  /products/{id}/reduce-stock:
    post:
      consumes:
      - application/json
      description: Reduce stock of a product by its ID with the provided quantity
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: string
      - description: Quantity to reduce
        in: query
        name: quantity
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.MessageResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperrors.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/apperrors.ErrorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/apperrors.ErrorResponse'
      summary: Reduce stock of a product by ID
      tags:
      - products
  /products/{id}/restore-stock:
    post:
      consumes:
      - application/json
      description: Restore stock of a product by its ID with the provided quantity
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: string
      - description: Quantity to restore
        in: query
        name: quantity
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.MessageResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperrors.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/apperrors.ErrorResponse'
      summary: Restore stock of a product by ID
      tags:
      - products
swagger: "2.0"
